In [215]:
import pandas as pd

In [217]:
df = pd.read_csv("nba_games.csv", index_col=0)

In [219]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,240.0,240.0,37.0,87.0,0.425,7.0,33.0,0.212,32.0,35.0,...,20.0,32.3,226.0,117.0,TOR,126,1,2023,2022-12-07,False
3,240.0,240.0,47.0,106.0,0.443,12.0,43.0,0.279,20.0,24.0,...,25.8,30.7,168.0,127.0,LAL,113,0,2023,2022-12-07,True
4,240.0,240.0,42.0,79.0,0.532,14.0,35.0,0.400,20.0,26.0,...,20.0,33.6,245.0,125.0,UTA,108,1,2023,2022-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,240.0,240.0,38.0,82.0,0.463,12.0,37.0,0.324,15.0,18.0,...,60.0,29.8,159.0,115.0,MEM,112,0,2017,2017-02-13,False
7282,240.0,240.0,34.0,95.0,0.358,7.0,33.0,0.212,17.0,23.0,...,59.2,34.5,231.0,103.0,LAC,108,1,2019,2018-10-19,False
7283,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
7284,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
7285,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [221]:
df = df.sort_values("date")
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
4602,240.0,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,...,66.7,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False
4603,240.0,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,...,50.0,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True
6370,240.0,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,...,50.0,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False
4155,240.0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,...,100.0,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False
4154,240.0,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,...,75.0,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6108,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,33.3,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False
3789,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,19.3,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False
3788,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,12.7,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True
4580,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,25.1,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True
4581,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,33.3,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False

In [223]:
df = df.reset_index(drop=True)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,...,66.7,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False
1,240.0,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,...,50.0,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True
2,240.0,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,...,50.0,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False
3,240.0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,...,100.0,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False
4,240.0,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,...,75.0,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,33.3,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False
7282,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,19.3,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False
7283,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,12.7,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True
7284,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,25.1,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True
7285,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,33.3,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False

In [225]:
del df["mp_opp.1"]
del df["index_opp"]

In [227]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,...,66.7,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False
1,240.0,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,...,50.0,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True
2,240.0,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,...,50.0,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False
3,240.0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,...,100.0,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False
4,240.0,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,...,75.0,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,33.3,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False
7282,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,19.3,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False
7283,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,12.7,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True
7284,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,25.1,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True
7285,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,33.3,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False

In [229]:
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1127067056.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("team", group_keys=False).apply(add_target)

In [231]:
df[df["team"] == "WAS"]

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
29,240.0,240.0,40.0,94.0,0.426,6.0,20.0,0.300,13.0,18.0,...,31.7,200.0,106.0,ATL,114,1,2017,2016-10-27,False,False
70,265.0,265.0,38.0,86.0,0.442,5.0,25.0,0.200,22.0,25.0,...,39.2,221.0,111.0,MEM,112,1,2017,2016-10-30,False,True
120,240.0,240.0,44.0,96.0,0.458,12.0,33.0,0.364,16.0,21.0,...,36.8,156.0,123.0,LAL,108,0,2017,2017-02-02,True,True
148,240.0,240.0,38.0,83.0,0.458,10.0,31.0,0.323,19.0,22.0,...,34.0,154.0,116.0,NOP,91,0,2017,2017-02-04,True,False
185,265.0,265.0,50.0,99.0,0.505,12.0,29.0,0.414,23.0,26.0,...,28.2,166.0,129.0,CLE,140,0,2017,2017-02-06,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7003,240.0,240.0,39.0,79.0,0.494,16.0,37.0,0.432,15.0,18.0,...,31.2,192.0,120.0,NYK,118,1,2023,2023-04-02,False,False
7007,240.0,240.0,50.0,99.0,0.505,13.0,27.0,0.481,15.0,21.0,...,37.5,208.0,126.0,MIL,140,0,2023,2023-04-04,False,False
7046,240.0,240.0,45.0,94.0,0.479,6.0,28.0,0.214,20.0,26.0,...,40.6,206.0,121.0,ATL,134,1,2023,2023-04-05,False,True
7063,240.0,240.0,39.0,84.0,0.464,7.0,33.0,0.212,29.0,37.0,...,44.5,149.0,117.0,MIA,108,0,2023,2023-04-07,True,False
7089,240.0,240.0,41.0,97.0,0.423,14.0,45.0,0.311,13.0,21.0,...,27.3,136.0,117.0,HOU,114,0,2023,2023-04-09,False,NaN

In [233]:
df["team"]

0       NYK
1       CLE
2       UTA
3       GSW
4       SAS
       ...
7281    MIA
7282    MIA
7283    BOS
7284    MIA
7285    BOS
Name: team, Length: 7286, dtype: object

In [235]:
df["target"][pd.isnull(df["target"])] = 2

/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1618397414.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2
/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [237]:
df["target"] = df["target"].astype(int, errors="ignore")

In [239]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,...,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False,1
1,240.0,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,...,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True,1
2,240.0,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,...,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False,1
3,240.0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,...,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False,1
4,240.0,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,...,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False,0
7282,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False,1
7283,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True,0
7284,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True,2
7285,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False,2

In [241]:
df["won"].value_counts()

won
False    3643
True     3643
Name: count, dtype: int64

In [243]:
df["target"].value_counts()

target
0    3629
1    3627
2      30
Name: count, dtype: int64

In [245]:
nulls = pd.isnull(df)

In [247]:
nulls = nulls.sum()

In [249]:
nulls = nulls[nulls > 0]

In [251]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [253]:
valid_columns

Index(['mp', 'mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=145)

In [255]:
df = df[valid_columns].copy()

In [257]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,240.0,32.0,87.0,0.368,9.0,27.0,0.333,15.0,20.0,...,36.8,200.0,101.0,CLE,117,1,2017,2016-10-25,False,1
1,240.0,240.0,45.0,94.0,0.479,13.0,35.0,0.371,14.0,19.0,...,36.8,153.0,125.0,NYK,88,0,2017,2016-10-25,True,1
2,240.0,240.0,40.0,82.0,0.488,8.0,24.0,0.333,16.0,16.0,...,39.2,220.0,120.0,POR,113,1,2017,2016-10-25,False,1
3,240.0,240.0,40.0,85.0,0.471,7.0,33.0,0.212,13.0,18.0,...,36.2,263.0,112.0,SAS,129,0,2017,2016-10-25,False,1
4,240.0,240.0,47.0,98.0,0.480,12.0,24.0,0.500,23.0,26.0,...,31.8,139.0,143.0,GSW,100,1,2017,2016-10-25,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,240.0,240.0,40.0,78.0,0.513,9.0,23.0,0.391,8.0,10.0,...,59.8,205.0,126.0,BOS,110,1,2023,2023-05-25,False,0
7282,240.0,240.0,33.0,93.0,0.355,14.0,30.0,0.467,23.0,29.0,...,32.9,164.0,129.0,BOS,104,0,2023,2023-05-27,False,1
7283,240.0,240.0,34.0,78.0,0.436,7.0,35.0,0.200,29.0,34.0,...,27.1,138.0,124.0,MIA,103,1,2023,2023-05-27,True,0
7284,240.0,240.0,42.0,86.0,0.488,14.0,28.0,0.500,5.0,6.0,...,35.6,264.0,121.0,BOS,84,1,2023,2023-05-29,True,2
7285,240.0,240.0,32.0,82.0,0.390,9.0,42.0,0.214,11.0,13.0,...,32.9,154.0,103.0,MIA,103,0,2023,2023-05-29,False,2

In [259]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [263]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits = 3)

sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [265]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [267]:
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [269]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [271]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.189744,0.502488,0.256098,CLE,0.523256,1.0,2017,2016-10-25,False,1
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.189744,0.268657,0.548780,NYK,0.186047,0.0,2017,2016-10-25,True,1
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.220513,0.601990,0.487805,POR,0.476744,1.0,2017,2016-10-25,False,1
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.182051,0.815920,0.390244,SAS,0.662791,0.0,2017,2016-10-25,False,1
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.125641,0.199005,0.768293,GSW,0.325581,1.0,2017,2016-10-25,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.484615,0.527363,0.560976,BOS,0.441860,1.0,2023,2023-05-25,False,0
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.139744,0.323383,0.597561,BOS,0.372093,0.0,2023,2023-05-27,False,1
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.065385,0.194030,0.536585,MIA,0.360465,1.0,2023,2023-05-27,True,0
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.174359,0.820896,0.500000,BOS,0.139535,1.0,2023,2023-05-29,True,2
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.139744,0.273632,0.280488,MIA,0.360465,0.0,2023,2023-05-29,False,2

In [273]:
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [277]:
predictors = list(selected_columns[sfs.get_support()])

In [279]:
predictors

['mp',
 'mp.1',
 '3p',
 'fta',
 'trb',
 'ast',
 'pf',
 'tov%',
 'usg%',
 'blk_max',
 'pf_max',
 '+/-_max',
 'blk%_max',
 'tov%_max',
 'mp_opp',
 '3p%_opp',
 'fta_opp',
 'ftr_opp',
 'ast%_opp',
 'blk%_opp',
 'usg%_opp',
 '3p_max_opp',
 'ft_max_opp',
 'orb_max_opp',
 'drb_max_opp',
 'trb_max_opp',
 'tov_max_opp',
 'drb%_max_opp',
 'blk%_max_opp',
 'ortg_max_opp']

In [293]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]
        
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis=1)
        combined.columns = ["actual", "prediction"]
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [313]:
predictions = backtest(df, rr, predictors)

In [315]:
predictions

      actual  prediction
1444       1           0
1445       0           1
1446       1           0
1447       0           1
1448       1           0
...      ...         ...
7281       0           0
7282       1           0
7283       0           0
7284       2           1
7285       2           1

[5842 rows x 2 columns]

In [323]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5363041982105987

In [325]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/3128703651.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.4381
1.0    0.5619
dtype: float64

In [327]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.189744,0.502488,0.256098,CLE,0.523256,1.0,2017,2016-10-25,False,1
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.189744,0.268657,0.548780,NYK,0.186047,0.0,2017,2016-10-25,True,1
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.220513,0.601990,0.487805,POR,0.476744,1.0,2017,2016-10-25,False,1
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.182051,0.815920,0.390244,SAS,0.662791,0.0,2017,2016-10-25,False,1
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.125641,0.199005,0.768293,GSW,0.325581,1.0,2017,2016-10-25,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.484615,0.527363,0.560976,BOS,0.441860,1.0,2023,2023-05-25,False,0
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.139744,0.323383,0.597561,BOS,0.372093,0.0,2023,2023-05-27,False,1
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.065385,0.194030,0.536585,MIA,0.360465,1.0,2023,2023-05-27,True,0
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.174359,0.820896,0.500000,BOS,0.139535,1.0,2023,2023-05-29,True,2
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.139744,0.273632,0.280488,MIA,0.360465,0.0,2023,2023-05-29,False,2

In [329]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [331]:
df_rolling

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.144,0.644610,0.189744,0.502488,0.256098,0.523256,1.0,False,NYK,2017
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.106,0.466382,0.189744,0.268657,0.548780,0.186047,0.0,True,CLE,2017
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.051,0.466382,0.220513,0.601990,0.487805,0.476744,1.0,False,UTA,2017
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.111,1.000000,0.182051,0.815920,0.390244,0.662791,0.0,False,GSW,2017
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.072,0.733191,0.125641,0.199005,0.768293,0.325581,1.0,True,SAS,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.262,0.288154,0.484615,0.527363,0.560976,0.441860,1.0,False,MIA,2023
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.054,0.138741,0.139744,0.323383,0.597561,0.372093,0.0,False,MIA,2023
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.062,0.068303,0.065385,0.194030,0.536585,0.360465,1.0,True,BOS,2023
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.117,0.200640,0.174359,0.820896,0.500000,0.139535,1.0,True,MIA,2023
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.060,0.288154,0.139744,0.273632,0.280488,0.360465,0.0,False,BOS,2023

In [333]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

def find_team_averages(team):
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys=False).apply(find_team_averages)

DataError: Cannot aggregate non-numeric type: object

In [335]:
df_rolling

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.144,0.644610,0.189744,0.502488,0.256098,0.523256,1.0,False,NYK,2017
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.106,0.466382,0.189744,0.268657,0.548780,0.186047,0.0,True,CLE,2017
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.051,0.466382,0.220513,0.601990,0.487805,0.476744,1.0,False,UTA,2017
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.111,1.000000,0.182051,0.815920,0.390244,0.662791,0.0,False,GSW,2017
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.072,0.733191,0.125641,0.199005,0.768293,0.325581,1.0,True,SAS,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.262,0.288154,0.484615,0.527363,0.560976,0.441860,1.0,False,MIA,2023
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.054,0.138741,0.139744,0.323383,0.597561,0.372093,0.0,False,MIA,2023
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.062,0.068303,0.065385,0.194030,0.536585,0.360465,1.0,True,BOS,2023
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.117,0.200640,0.174359,0.820896,0.500000,0.139535,1.0,True,MIA,2023
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.060,0.288154,0.139744,0.273632,0.280488,0.360465,0.0,False,BOS,2023

In [337]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)

In [339]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.144,0.644610,0.189744,0.502488,0.256098,0.523256,1.0,False,NYK,2017
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.106,0.466382,0.189744,0.268657,0.548780,0.186047,0.0,True,CLE,2017
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.051,0.466382,0.220513,0.601990,0.487805,0.476744,1.0,False,UTA,2017
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.111,1.000000,0.182051,0.815920,0.390244,0.662791,0.0,False,GSW,2017
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.072,0.733191,0.125641,0.199005,0.768293,0.325581,1.0,True,SAS,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.262,0.288154,0.484615,0.527363,0.560976,0.441860,1.0,False,MIA,2023
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.054,0.138741,0.139744,0.323383,0.597561,0.372093,0.0,False,MIA,2023
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.062,0.068303,0.065385,0.194030,0.536585,0.360465,1.0,True,BOS,2023
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.117,0.200640,0.174359,0.820896,0.500000,0.139535,1.0,True,MIA,2023
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.060,0.288154,0.139744,0.273632,0.280488,0.360465,0.0,False,BOS,2023

In [341]:
df = df.dropna()

In [343]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.144,0.644610,0.189744,0.502488,0.256098,0.523256,1.0,False,NYK,2017
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.106,0.466382,0.189744,0.268657,0.548780,0.186047,0.0,True,CLE,2017
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.051,0.466382,0.220513,0.601990,0.487805,0.476744,1.0,False,UTA,2017
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.111,1.000000,0.182051,0.815920,0.390244,0.662791,0.0,False,GSW,2017
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.072,0.733191,0.125641,0.199005,0.768293,0.325581,1.0,True,SAS,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.262,0.288154,0.484615,0.527363,0.560976,0.441860,1.0,False,MIA,2023
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.054,0.138741,0.139744,0.323383,0.597561,0.372093,0.0,False,MIA,2023
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.062,0.068303,0.065385,0.194030,0.536585,0.360465,1.0,True,BOS,2023
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.117,0.200640,0.174359,0.820896,0.500000,0.139535,1.0,True,MIA,2023
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.060,0.288154,0.139744,0.273632,0.280488,0.360465,0.0,False,BOS,2023

In [345]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))
/var/folders/jn/kjpxydnn7mv7lk9_v6glkk_h0000gn/T/ipykernel_35107/1688004556.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team", group_keys=False).apply(lambda x: shift_col(x, col_name))

In [347]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10,team_10,season_10,home_next,team_opp_next,date_next
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.502488,0.256098,0.523256,1.0,False,NYK,2017,1.0,MEM,2016-10-29
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.268657,0.548780,0.186047,0.0,True,CLE,2017,0.0,TOR,2016-10-28
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.601990,0.487805,0.476744,1.0,False,UTA,2017,1.0,LAL,2016-10-28
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.815920,0.390244,0.662791,0.0,False,GSW,2017,0.0,NOP,2016-10-28
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.199005,0.768293,0.325581,1.0,True,SAS,2017,0.0,SAC,2016-10-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.527363,0.560976,0.441860,1.0,False,MIA,2023,1.0,BOS,2023-05-27
7282,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.323383,0.597561,0.372093,0.0,False,MIA,2023,0.0,BOS,2023-05-29
7283,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.194030,0.536585,0.360465,1.0,True,BOS,2023,1.0,MIA,2023-05-29
7284,0.0,0.0,0.500000,0.396552,0.523923,0.464286,0.326923,0.639769,0.095238,0.098039,...,0.820896,0.500000,0.139535,1.0,True,MIA,2023,NaN,None,None
7285,0.0,0.0,0.261905,0.327586,0.289474,0.285714,0.596154,0.227666,0.238095,0.235294,...,0.273632,0.280488,0.360465,0.0,False,BOS,2023,NaN,None,None

In [349]:
df = df.copy()

In [351]:
full = df.merge(df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
                left_on=["team", "date_next"],
                right_on=["team_opp_next", "date_next"])

In [353]:
full

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,team_10_y,season_10_y,team_opp_next_y,team_y
0,0.0,0.0,0.261905,0.413793,0.236842,0.285714,0.307692,0.399135,0.333333,0.372549,...,0.082051,0.189055,0.475610,0.302326,0.0,True,MEM,2017,NYK,MEM
1,0.0,0.0,0.571429,0.534483,0.502392,0.428571,0.461538,0.453890,0.309524,0.352941,...,0.217949,0.353234,0.524390,0.220930,0.0,True,TOR,2017,CLE,TOR
2,0.0,0.0,0.452381,0.327586,0.523923,0.250000,0.250000,0.399135,0.357143,0.294118,...,0.206410,0.597015,0.597561,0.488372,0.0,True,LAL,2017,UTA,LAL
3,0.0,0.0,0.452381,0.379310,0.483254,0.214286,0.423077,0.224784,0.285714,0.333333,...,0.042308,0.253731,0.268293,0.406977,0.0,False,NOP,2017,GSW,NOP
4,0.0,0.0,0.619048,0.603448,0.504785,0.392857,0.250000,0.639769,0.523810,0.490196,...,0.144872,0.432836,0.524390,0.255814,1.0,True,SAC,2017,SAS,SAC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,0.0,0.0,0.523810,0.362069,0.581340,0.607143,0.653846,0.495677,0.261905,0.333333,...,0.750000,0.611940,0.463415,0.511628,0.0,False,MIA,2023,BOS,MIA
7250,0.0,0.0,0.452381,0.275862,0.566986,0.535714,0.538462,0.510086,0.309524,0.352941,...,0.484615,0.527363,0.560976,0.441860,1.0,False,MIA,2023,BOS,MIA
7251,0.0,0.0,0.452381,0.258621,0.583732,0.285714,0.230769,0.482709,0.166667,0.176471,...,0.173077,0.368159,0.731707,0.290698,0.0,True,BOS,2023,MIA,BOS
7252,0.0,0.0,0.285714,0.517241,0.205742,0.464286,0.365385,0.592219,0.523810,0.549020,...,0.065385,0.194030,0.536585,0.360465,1.0,True,BOS,2023,MIA,BOS
7253,0.0,0.0,0.309524,0.258621,0.399522,0.214286,0.461538,0.207493,0.666667,0.647059,...,0.139744,0.323383,0.597561,0.372093,0.0,False,MIA,2023,BOS,MIA

In [355]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

     team_x team_opp_next_x team_y team_opp_next_y   date_next
0       NYK             MEM    MEM             NYK  2016-10-29
1       CLE             TOR    TOR             CLE  2016-10-28
2       UTA             LAL    LAL             UTA  2016-10-28
3       GSW             NOP    NOP             GSW  2016-10-28
4       SAS             SAC    SAC             SAS  2016-10-27
...     ...             ...    ...             ...         ...
7249    BOS             MIA    MIA             BOS  2023-05-25
7250    BOS             MIA    MIA             BOS  2023-05-27
7251    MIA             BOS    BOS             MIA  2023-05-27
7252    MIA             BOS    BOS             MIA  2023-05-29
7253    BOS             MIA    MIA             BOS  2023-05-29

[7254 rows x 5 columns]

In [357]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [359]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'team_10_x',
 'team_opp_next_x',
 'date_next',
 'team_10_y',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [361]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [363]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [365]:
predictors = list(selected_columns[sfs.get_support()])

In [367]:
predictors

['3p%',
 'orb%',
 'usg%',
 'fg_max',
 'fta_max',
 'gmsc_max',
 'ortg_max',
 'ft%_opp',
 'stl_opp',
 'usg%_opp',
 'trb_max_opp',
 'trb%_max_opp',
 '3p%_10_x',
 'usg%_10_x',
 'fg_max_10_x',
 'fta_max_10_x',
 'gmsc_max_10_x',
 'ortg_max_10_x',
 'ft%_opp_10_x',
 'stl_opp_10_x',
 'usg%_opp_10_x',
 'trb_max_opp_10_x',
 'trb%_max_opp_10_x',
 'home_next',
 '3p%_10_y',
 'ast%_10_y',
 'usg%_10_y',
 'gmsc_max_10_y',
 'usg%_opp_10_y',
 'ft%_max_opp_10_y']

In [369]:
predictions = backtest(full, rr, predictors)

In [371]:
accuracy_score(predictions["actual"], predictions["prediction"])

0.5774260151410874